"""empty message

Revision ID: 129fbb501b0f
Revises: 
Create Date: 2021-06-26 17:24:42.374284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '129fbb501b0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user', 'created_time',
               existing_type=mysql.INTEGER(),
               comment='',
               existing_nullable=True)
    op.alter_column('sys_user', 'created_user',
               existing_type=mysql.VARCHAR(length=50),
               comment='',
               existing_nullable=True)
    op.alter_column('sys_user', 'del_flag',
               existing_type=mysql.INTEGER(),
               comment='',
               existing_nullable=True)
    op.alter_column('sys_user', 'updated_time',
               existing_type=mysql.INTEGER(),
               comment='',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sys_user', 'updated_time',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('sys_user', 'del_flag',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('sys_user', 'created_user',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    op.alter_column('sys_user', 'created_time',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=True)
    # ### end Alembic commands ###
