"""empty message

Revision ID: fb8d785807ce
Revises: 
Create Date: 2021-08-01 23:06:34.199483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb8d785807ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jd_goods_info',
    sa.Column('uuid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True, comment='商品编码'),
    sa.Column('name', sa.String(length=256), nullable=True, comment='商品名称'),
    sa.Column('skuid', sa.String(length=50), nullable=True, comment='商品id'),
    sa.Column('is_jd_sale', sa.String(length=16), nullable=True, comment='是否京东自营'),
    sa.Column('img_url', sa.String(length=256), nullable=True, comment='图片链接'),
    sa.Column('best_price', sa.String(length=32), nullable=True, comment='活动价格'),
    sa.Column('unit_price', sa.String(length=32), nullable=True, comment='京东单价'),
    sa.Column('catagory', sa.String(length=50), nullable=True, comment='商品类别'),
    sa.Column('material_url', sa.String(length=256), nullable=True, comment='商品链接'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='活动开始时间'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='活动结束时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jd_goods_info')
    # ### end Alembic commands ###
