"""empty message

Revision ID: fd7ae5213225
Revises: 
Create Date: 2021-06-26 21:20:43.432677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7ae5213225'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jd_goods_info',
    sa.Column('uuid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True, comment='商品编码'),
    sa.Column('name', sa.String(length=256), nullable=True, comment='商品名称'),
    sa.Column('skuid', sa.String(length=50), nullable=True, comment='商品id'),
    sa.Column('is_jd_sale', sa.String(length=16), nullable=True, comment='是否京东自营'),
    sa.Column('img_url', sa.String(length=256), nullable=True, comment='图片链接'),
    sa.Column('best_price', sa.String(length=32), nullable=True, comment='活动价格'),
    sa.Column('unit_price', sa.String(length=32), nullable=True, comment='京东单价'),
    sa.Column('catagory', sa.String(length=50), nullable=True, comment='商品类别'),
    sa.Column('material_url', sa.String(length=256), nullable=True, comment='商品链接'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='活动开始时间'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='活动结束时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('sys_user',
    sa.Column('uuid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True, comment='账号'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('salt', sa.String(length=16), nullable=True, comment='密码盐'),
    sa.Column('password', sa.String(length=32), nullable=True, comment='入库密码'),
    sa.Column('del_flag', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.Column('updated_time', sa.Integer(), nullable=True),
    sa.Column('created_user', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_user')
    op.drop_table('jd_goods_info')
    # ### end Alembic commands ###
